### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by TheGreatSardini** [arvitus/NoSpawnerChange#1]
hello, I LOVE the idea of this!!
But I can't seem to get it to work at all. 
Fresh 1.21 Fabric client, + this mod
New world. 
In adventure mode it works to add  /give @a minecraft:chicken_spawn_egg[can_place_on={blocks:'spawner'}] and without it does not let me place. 
But in Survival, it just always lets me place spawn eggs in spawners overriting the existing. 

Is there a prerequisite that this needs to allow the mixins to work?

**Comment by arvitus** [comment]
Hi, yeah it seems like it does not work in singleplayer. It's intended to be used on servers, but I can make it work with singleplayer too. Just have to figure out how :)

**Comment by arvitus** [comment]
Fixed in [v1.0.1](https://github.com/arvitus/NoSpawnerChange/releases/tag/1.0.1)

**Comment by TheGreatSardini** [comment]
is there any way to make it where you can place eggs on blank spawners but not spawners that already have assigned mob?
your fix did make it work in singleplayer but sadly seems to block both empty and assigned :)

**Comment by arvitus** [comment]
I think this should be possible. I'll see what I can do :)

**Comment by arvitus** [comment]
You can download the new version here: https://modrinth.com/mod/nospawnerchange/version/1.1.0
I added a config so you can choose what features you want. If you have any other suggestions, please open another issue.
